name: Sync Strava Data
on:
  workflow_dispatch:
    inputs:
      activity_count:
        description: 'Number of activities to sync'
        default: '30'
        required: false
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Debug environment variables
        run: |
          echo "Checking environment variables..."
          echo "TEST_SECRET is set: $([[ -n "$TEST_SECRET" ]] && echo "yes" || echo "no")"
          echo "STRAVA_CLIENT_ID is set: $([[ -n "$STRAVA_CLIENT_ID" ]] && echo "yes" || echo "no")"
          echo "GOOGLE_SHEETS_ID is set: $([[ -n "$GOOGLE_SHEETS_ID" ]] && echo "yes" || echo "no")"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}

      - name: Sync Strava activities
        run: npm start ${{ github.event.inputs.activity_count || '30' }}
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_TOKEN_EXPIRES_AT: ${{ secrets.STRAVA_TOKEN_EXPIRES_AT }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}